# Volume widget
AnchorLayout:
	id: volumebox
	anchor_y: 'center'
	anchor_x: 'center'
	size_hint: 1, 1
	opacity: 0
	BoxLayout:
		size_hint: 0.6, 0.15
		canvas.before:
			Color:
				rgba: 0.5,0.5,0.5,0.5
			Rectangle:
				pos: self.pos
				size: self.size
		InfoLabel:
			size_hint: 0.2, 1
			text: 'Vol:'
		ProgressBar:
			id: volume
			max: 32
			value: 0
			size_hint: 0.65, 1
		InfoLabel:
			id: volumetext
			size_hint: 0.15, 1
